### ISSUE TITLE
Temp dir management

### ISSUE THREAD

**Issue by ignazas** [CentroFM/AudioLogger#16]
On start:
Ask users permission to delete all files from temp dir matching *-*.mp3 and *-*.wav mask;

After conversion wav -> mp3:
Delete wav;

After upload:
Delete mp3;

On stop/exit:
Convert last file;
Upload last file;
Ask users permission to delete all files from temp dir matching *-*.mp3 and *-*.wav mask;

**Comment by DevBlox** [comment]
Everything is working as expected
