### ISSUE TITLE
Redundancy?

### ISSUE THREAD

**Issue by DevBlox** [CentroFM/AudioLogger#25]
If the upload location already has quite a few recordings, a simple error in the logger application can make them all disappear in an instant. This should be handled somehow.

**Possible ways:**
- Make some "triggers" in the application if there are many files about to be deleted
- Constantly make snapshots of collected data (requires more storage, though if the mistake went have gone unnoticed, it could destroy that too)

**Comment by ignazas** [comment]
To prevent time setting glitch:
1. During application start it should always ask if any files to be deleted.
If no response from user for 5 min. (unattended service) files shall be copied to /old subdir.
2. If during normal operation amount of files to be deleted is greater than 25, check if time span between first and last file is not greater than 24 hours. If TRUE - ask user (first method).

**Comment by DevBlox** [comment]
**A/C**
- The user is prompted if any files are to be deleted
- At recording start, check how many files are about to be deleted, if many, warn the user
- If any failures during upload occur, or user chooses not to delete any files, they should be preserved in a separate directory.

**Comment by DevBlox** [comment]
Features complete
