### ISSUE TITLE
No recording alignment to time

### ISSUE THREAD

**Issue by ignazas** [CentroFM/AudioLogger#28]
Aš buvau padarės, kad nustacius 20 min failo dydi, programa rasytu iki pirmo islyginimo tasko (paspadus "rasyti" 11:11, rasytu iki 11:20), o veliau failai butu 11:20-11:40, 11:40-12:00 ir tt.
dabar matau, kad taip nesidaro.

**Comment by DevBlox** [comment]
Hm, keista. As visiskai nelieciau laiko skaiciavimo, matyt praleidau kazkokia vieta kai konvertavima keiciau. Paziuresiu kaip kas ten, jei reiks pakeisiu visa sistema laiko skaiciavimo

**Comment by ignazas** [comment]
Na, matau, kad nustacius 7 dienu spana ir 60min intervalus viskas veikia puikiai bet alignmento nera.

**Comment by devblok** [comment]
Continued on issue #39
